### ISSUE TITLE
No longer work in Foundry 9.238

### ISSUE THREAD

**Issue by sanpats** [League-of-Foundry-Developers/fvtt-initiative-double-click#6]
It works correctly in Foundry 0.8.9. Now, I can still double click to edit the initiative, but the new value won't registered.

**Comment by oestred** [comment]
Confirmed the same issue.

**Comment by pj-squirrel** [comment]
Can confirm this happens, even with every other module disabled.
This is the error I get when I try to update initiative via double click:

Uncaught TypeError: game.combat.updateCombatant is not a function  
[Detected 1 package: initiative-double-click]  
    at HTMLInputElement.<anonymous> (Combat.js:23)  
    at HTMLInputElement.dispatch (jquery.min.js:2)  
    at HTMLInputElement.v.handle (jquery.min.js:2)

**Comment by CaosFR** [comment]
Same for me

**Comment by mclemente** [comment]
Issue should be fixed now, according to #7
